name: "[DataCap Refresh]"
description: Allocator's Request for a review of DC allocations
title: "[DataCap Refresh] <1st/2nd/3rd> Review of <Allocator Organization Name>"
labels: [Refresh]
assignees:
  - Kevin-FF-USA
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Before you start:**  
        Please edit the issue title above, replacing:
        - `<1st/2nd/3rd>` with your current review number (e.g., 1st, 2nd, 3rd)
        - `<Allocator Organization Name>` with the name of your organization
        - DO NOT REMOVE [DataCap Refresh] please

  - type: dropdown
    id: audit_type
    attributes:
      label: "What type of Audit did you opt into? Choose from dropdown"
      options:
        - Enterprise Data
        - Public Open Data
        - Market Based Allocator
        - Automated Allocator
    validations:
      required: true

  - type: input
    id: json_number
    attributes:
      label: "What is your JSON hash (starts with 'rec'). If you don't remember or remember only the v5 json name (which was a number), check your allocator json name here Allocator Applications/json_names_lookup.md"
      placeholder: "DO NOT POST A URL, paste the name of your json that is a hash that starts with 'rec'"
    validations:
      required: true

  - type: input
    id: allocator_application
    attributes:
      label: "Link to your allocator operations description"
      placeholder: "https://..."
      description: "Link to client diligence, dispute resolution, etc., published per policy: https://github.com/filecoin-project/Allocator-Governance?tab=readme-ov-file#programmatic-policies"
    validations:
      required: true

  - type: input
    id: compliance_report
    attributes:
      label: "Compliance Report"
      placeholder: "https://datacapstats.io/allocators/..."
      description: "Link to your latest report from https://datacapstats.io/allocators/"
    validations:
      required: true

  - type: textarea
    id: previous_reviews
    attributes:
      label: "Previous Reviews"
      description: "Paste each entry as 'Link + Outcome' (e.g., 5 PiB)"
      value: |
        - [1st review] <link to the review> Outcome: <how many> PiB
        - [2nd review] <link to the review> Outcome: <how many> PiB
        _(Add more review blocks as needed)_
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Current Allocation Distribution

  - type: textarea
    id: allocation_table
    attributes:
      label: "Client Allocation Table"
      description: "Enter client names and DataCap granted for this review round"
      value: |
        | Client name | DC granted |
        | ----------- | ---------- |
        | Client 1    | 0 PiB      |
        | Client 2    | 0 PiB      |
        | Client 3    | 0 PiB      |
    validations:
      required: true
      
  - type: textarea
    id: client_breakdowns
    attributes:
      label: "Client-specific Breakdown"
      description: "Complete the following I–V format for each client you allocated to"
      value: |
        #### Client 1

        I. [Client Name](link)  
        - DC requested:  
        - DC granted so far:  

        II. **Dataset Completion**  
        (Provide deal(s) containing sample(s) of data)

        III. **SP Match**  
        (Does the list of SPs provided match the list in the CID report?)

        IV. **Replica Count**  
        Promised vs delivered:  

        V. **SP Retrieval Performance**  
        | SP ID  | % retrieval | Meets >75%? |
        |--------|-------------|--------------|
        | f01234 | 83%         | YES          |

        ---

        #### Client 2

        I. [Client Name](link)  
        - DC requested:  
        - DC granted so far:  

        II. **Dataset Completion**  
        (Provide deal(s) containing sample(s) of data)

        III. **SP Match**  
        (Does the list of SPs provided match the list in the CID report?)

        IV. **Replica Count**  
        Promised vs delivered:  

        V. **SP Retrieval Performance**  
        | SP ID  | % retrieval | Meets >75%? |
        |--------|-------------|--------------|
        | f05678 | 91%         | YES          |

        ---

        _(Add more client blocks as needed)_
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        ### Allocation Summary

  - type: textarea
    id: allocator_notes
    attributes:
      label: "Notes from the Allocator"
      description: "Mention any events or anomalies during the allocation round"
    validations:
      required: true

  - type: textarea
    id: issues_reported
    attributes:
      label: "Issues or discrepancies reported?"
      placeholder: "Yes/No. If Yes, please describe."
    validations:
      required: true

  - type: textarea
    id: risk_mitigation
    attributes:
      label: "Steps to minimize unfair or risky practices"
      description: "Describe your due diligence and how unfaithful users are screened out"
    validations:
      required: true

  - type: textarea
    id: value_to_filecoin
    attributes:
      label: "Value to the Filecoin ecosystem"
      description: "Describe the value added through this allocation round, beyond your original application"
    validations:
      required: true
      
  - type: dropdown
    id: maintained_standards
    attributes:
      label: "Confirm you maintained your application standards for all client allocations"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    id: diligence_review
    attributes:
      label: "Do you understand that a diligence review will follow and require updates to this issue?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true
